### PR TITLE
OSOE-370: Use GitHub activity-specific remote link title in Jira

### LINKED ISSUE #52: Use GitHub activity-specific remote link title in Jira (OSOE-370)
In `create-jira-issues-for-community-activities` currently all remote links under Jira issues that point to GitHub resources have the title "GitHub resource". Change this so the title is specific to the type of activity:

- "GitHub issue" for issues.
- "GitHub discussion" for discussions.
- "GitHub pull request" for PRs.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-370)

### PR DESCRIPTION
**Pull request by Piedone**
OSOE-370
Fixes #52.

### CODE REVIEW

**Comment by sarahelsaig** [comment]
I think the value of `$linkTitle` should be Title Case? I know you don't like that for some reason... why tho?

**Comment by Piedone** [comment]
Both title styles are valid, but in Jira what we usually use is not that.

**Comment by sarahelsaig** [comment]
If that's a royal we, then yeah sure.

**Comment by Piedone** [comment]
I checked out our running projects and the overwhelming majority of issues don't use Title Case. So, it's a democratic "we" :D.

**Pull request merged**
