### PR TITLE
OSOE-769: Trigger validate-pull-request on pull_request_target

### LINKED ISSUE #304: Trigger validate-pull-request on pull_request_target (OSOE-769)
The [`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) trigger is better than `pull_request`, since it also works for forks, and without approval. That's what we actually need.

Then [this line](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/check-merge-conflict/action.yml#L11) in `check-merge-conflict` can be adjusted too.

Same for `validate-submodule-pull-request`.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-769)

### PR DESCRIPTION
**Pull request by Piedone**
Fixes #304
OSOE-769

### CODE REVIEW

**Comment by BenedekFarkas** [comment]
Wouldn't these changes prevent our team members from testing their own PRs' changes to the `validate(-submodule)-pull-request` workflow?

**Comment by Piedone** [comment]
Yes, for testing those you'd need to change the trigger. There's unfortunately no way around this.

**Comment by BenedekFarkas** [comment]
OK, I'm trying to picture in my head what the effect of this will be exactly. If all the triggers are updated, including `validate-pull-request` in OSOCE and `validate-this-pull-request` in LGHA, then changes made to those can't be tested in a PR at all. **Is that right?**

For example, if I work on the `validate-pull-request` reusable workflow, I'd also update the branch references in the workflows that call it, including in OSOCE in LGHA, but this way OSOCE and LGHA will still run on the target (usually default branch).

Can this be circumvented by making changes (with malicious intent to extract a secret/token) by opening a second PR that targets my first one with the bad code?

**Comment by Piedone** [comment]
Those changes won't be possible to test without doing anything, but will be possible to test after changing the workflow's trigger from `pull_request_target` to `pull_request` (and possibly [this](https://github.com/Lombiq/GitHub-Actions/blob/b34f78ec10f1870bb0777819daca21954ef6e36a/.github/workflows/validate-pull-request.yml#L24) and [this](https://github.com/Lombiq/GitHub-Actions/blob/b34f78ec10f1870bb0777819daca21954ef6e36a/.github/workflows/validate-submodule-pull-request.yml#L28) too, but you'll need to change `opened` here anyway unless you want to open a new PR for every test run).

I guess so, yes, an external actor can open a PR targeting an issue branch that has the `pull_request` trigger like this. However, just as with PRs today, the workflow there wouldn't run until one of our team members goes there and approves the run.

The point of these changes is to allow running Validate Pull Request right when opening the PR (i.e. without anybody clicking the "Approve and run" button there) even for external contributors. This wouldn't be safely possible with `pull_request` (since that would run the workflow code in the PR) and thus GitHub doesn't allow it. It is safe though with `pull_request_target` (since that runs the workflow code of the target branch, but only if the target branch already uses `pull_request_target`).

**Comment by BenedekFarkas** [comment]
> but only if the target branch already uses `pull_request_target`

OK, thanks, this was the missing piece for me.

**Review by BenedekFarkas — APPROVED** [review]

**Pull request merged**
